# name of your github action
name: CI
# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the electron branch
      - v2.0.x
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: v2.0.x
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: see directory
        run: ls

  build_on_win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          ref: v2.0.x
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: see directory
        run: ls
