# name of your github action
name: CI
# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the electron branch
      - v2.0.x
# this is where the magic happens, each job happens in parallel btw
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [macOS-latest]
    env:
      ELECTRON_CACHE: '~/.cache/electron'
      ELECTRON_BUILDER_CACHE: '~/.cache/electron-builder'

    steps:
      - uses: actions/checkout@master
        with:
          ref: v2.0.x

      - uses: actions/setup-node@master
        with:
          node-version: 12.13


      - name: Get npm cache directory
        id: npm-cache-setup
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-setup.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/cache@v1
        id: electron-cache
        with:
          path: '~/.cache/electron'
          key: ${{ runner.os }}-electron
          restore-keys: |
            ${{ runner.os }}-electron

      - uses: actions/cache@v1
        id: electron-builder-cache
        with:
          path: '~/.cache/electron-builder'
          key: ${{ runner.os }}-electron-builder
          restore-keys: |
            ${{ runner.os }}-electron-builder


      #      - name: install node tools
      #        if: matrix.os == 'windows-latest'
      #        run: npm install --global --production windows-build-tools@4.0.0

      - name: Install dependencies
        run: npm ci

      - name: Build on ${{ matrix.os }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron:build -- --publish always
