# name of your github action
name: Lint pull request
# this will help you specify where to run
on:
  pull_request:
    branches:
      # this will run on the electron branch
      - v2.0.x
# this is where the magic happens, each job happens in parallel btw
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: v2.0.x

      - uses: actions/setup-node@master
        with:
          node-version: 12.13

      - name: Get npm cache directory
        id: npm-cache-setup
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-setup.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
