# name of your github action
name: Lint
# this will help you specify where to run
on:
  push:
    paths:
      - '**.ts'
      - '**.vue'
  pull_request:
    paths:
      - '**.ts'
      - '**.vue'

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2



      - uses: actions/setup-node@v1
        with:
          node-version: 12.13



      - name: Get npm cache directory
        id: npm-cache-setup
        run: |
          echo "::set-output name=dir::$(npm config get cache)"



      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-setup.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-



      - name: Install dependencies
        run: npm ci



      - name: Lint
        run: npm run lint -- --no-fix
